







sounds = [
    'Afarin',
    'AreBarandeShodim',
    'AreFekreKhoobieh',
    'Bale',
    'AreManEshtebhGoftam',
    'asabanimishe',
    'Asabani Shod',
    'avalman',
    'avaltobegoo',
    'barandehshodim',
    'moafegham',
    'basheshorookon',
    'BebinEshtebahGoftiSekehKam',
    'behemonsekehmide',
    'salaam',
    'Snore',
    'berimmarhalebad',
    'beshinpishema',
    'dorostgofti',
    'beshinsandali',
    'biabazibob',
    'chap',
    'rast',
    'vasat',
    'EsmetChieh',
    'halanobatemane',
    'havasetojamkon',
    'hooradorostbood',
    'hoselam',
    'khastehshodam',
    'kheilibobdoost',
    'khoobi',
    'mamnoontokhoobi',
    'marhalehtamoom',
    'nabayaddad',
    'saketbashi',
    'sekehamonziadshod',
    'zoodbashbegoo',
    'Ahoo',
    'Asb',
    'Babr',
    'Gav',
    'Gorbeh',
    'Gorg',
    'Gosfand',
    'Khargoosh',
    'Khoroos',
    'Morgh',
    'Palang',
    'Roobah',
    'Sag',
    'Shir',
    'Ananas',
    'Angoor',
    'Gilas',
    'Golabi',
    'Hendoone',
    'Holoo',
    'Khiar',
    'Kivi',
    'Moz',
    'Porteghal',
    'Sib',
    'Zardaloo',
    'Abroo',
    'Angosht',
    'Bazoo',
    'Cheshm',
    'Dast',
    'Gardan',
    'Goosh',
    'Lab',
    'Pa',
    'Sar',
    'Shekam'
]
